# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1363, 901)
        MainWindow.setStyleSheet("*{background-color: rgb(255, 255, 255);}\n"
"QFrame#frame{background-color: rgb(86, 109, 151);}\n"
"/*#frame_2{background-color: rgb(238, 241, 246);}*/\n"
"#frame_3{\n"
"    background-color: rgba(177, 177, 177, 100);\n"
"    background: transparent;\n"
"}\n"
"#frame_4{background: transparent;}\n"
"QGroupBox#groupBox_2{background: transparent;}\n"
"#groupBox_5{background: transparent;}\n"
"#titleGroupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(198, 198, 198);\n"
"}\n"
"QWidget#page_2{background-color: rgb(238, 241, 246);}\n"
"QLabel#softwareNameLabel{\n"
"    background: transparent;\n"
"    color: rgb(232, 233, 234);\n"
"    font: 14pt \"hooge 05_54\";\n"
"}\n"
"\n"
"#btnLoadData{\n"
"    border-radius: 18px;\n"
"    background-color: rgb(0, 151, 63);\n"
"    font: 87 12pt \"Source Han Serif SC Heavy\";\n"
"    font: 12pt \"方正粗黑宋简体\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"}\n"
"#btnLoadData:hover{\n"
"    background-color: rgb(0, 126, 52);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btnLoadData:pressed{\n"
"    background-color: rgb(0, 108, 45);\n"
"}\n"
"#StrangerButton{\n"
"    background-color: rgb(255, 216, 1);\n"
"    background-color: rgb(227, 46, 46);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 18px;\n"
"    font: 11pt \"方正粗黑宋简体\";\n"
"}\n"
"#StrangerButton:checked{\n"
"    background-color: rgb(186, 38, 38);\n"
"}\n"
"#CameraButton{\n"
"    background-color: rgb(255, 216, 1);\n"
"    background-color: rgb(227, 46, 46);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 18px;\n"
"    font: 11pt \"方正粗黑宋简体\";\n"
"}\n"
"#CameraButton:hover{background-color: rgb(199, 41, 41);}\n"
"#CameraButton:pressed{background-color: rgb(186, 38, 38);}\n"
"#maxiButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}\n"
"#maxiButton:hover{background-color: rgb(222, 222, 222);}\n"
"#maxiButton:pressed{background-color: rgb(189, 189, 189);}\n"
"#miniButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    image: url(:/home/icon/blackminus.png);\n"
"}\n"
"#miniButton:hover{background-color: rgb(222, 222, 222);}\n"
"#miniButton:pressed{background-color: rgb(189, 189, 189);}\n"
"#closeButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    image: url(:/home/icon/blackclose.png);\n"
"}\n"
"#closeButton:hover{background-color: rgb(222, 222, 222);}\n"
"#closeButton:pressed{background-color: rgb(189, 189, 189);}\n"
"QPushButton#page1Button{\n"
"    border: none;\n"
"    background: transparent;\n"
"    font: 87 14pt \"Source Han Serif SC Heavy\";\n"
"    font: 16pt \"方正粗黑宋简体\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"    padding: 16px;\n"
"    text-align: left;\n"
"    padding-left: 22px;\n"
"}\n"
"#page1Button:hover{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#page1Button:checked{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"    border-left: 6px solid rgb(97, 168, 62);\n"
"    padding-left: 16px;\n"
"}\n"
"#page2Button{\n"
"    border: none;\n"
"    background: transparent;\n"
"    font: 87 14pt \"Source Han Serif SC Heavy\";\n"
"    font: 16pt \"方正粗黑宋简体\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"    padding: 16px;\n"
"    text-align: left;\n"
"    padding-left: 22px;\n"
"}\n"
"#page2Button:hover{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#page2Button:checked{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"    border-left: 6px solid rgb(97, 168, 62);\n"
"    padding-left: 16px;\n"
"}\n"
"#page4Button{\n"
"    border: none;\n"
"    background: transparent;\n"
"    font: 87 14pt \"Source Han Serif SC Heavy\";\n"
"    font: 16pt \"方正粗黑宋简体\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"    padding: 16px;\n"
"    text-align: left;\n"
"    padding-left: 22px;\n"
"}\n"
"#page4Button:hover{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#page4Button:checked{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"    border-left: 6px solid rgb(97, 168, 62);\n"
"    padding-left: 16px;\n"
"}\n"
"#page5Button{\n"
"    border: none;\n"
"    background: transparent;\n"
"    font: 87 14pt \"Source Han Serif SC Heavy\";\n"
"    font: 16pt \"方正粗黑宋简体\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"    padding: 16px;\n"
"    text-align: left;\n"
"    padding-left: 22px;\n"
"}\n"
"#page5Button:hover{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#page5Button:checked{\n"
"    background-color: rgb(62, 78, 108);\n"
"    color: rgb(255, 255, 255);\n"
"    border-left: 6px solid rgb(97, 168, 62);\n"
"    padding-left: 16px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#frame {border: none;}\n"
"#frame_3 {border: none;}\n"
"#frame_2 {border: none;}\n"
"#groupBox_2 {border: none;}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.softwareNameLabel = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.softwareNameLabel.sizePolicy().hasHeightForWidth())
        self.softwareNameLabel.setSizePolicy(sizePolicy)
        self.softwareNameLabel.setText("")
        self.softwareNameLabel.setPixmap(QtGui.QPixmap(":/login/icon/applabel.png"))
        self.softwareNameLabel.setObjectName("softwareNameLabel")
        self.verticalLayout_9.addWidget(self.softwareNameLabel)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.page1Button = QtWidgets.QPushButton(self.groupBox_2)
        self.page1Button.setCheckable(True)
        self.page1Button.setChecked(False)
        self.page1Button.setObjectName("page1Button")
        self.verticalLayout.addWidget(self.page1Button)
        self.page2Button = QtWidgets.QPushButton(self.groupBox_2)
        self.page2Button.setCheckable(True)
        self.page2Button.setObjectName("page2Button")
        self.verticalLayout.addWidget(self.page2Button)
        self.page4Button = QtWidgets.QPushButton(self.groupBox_2)
        self.page4Button.setCheckable(True)
        self.page4Button.setObjectName("page4Button")
        self.verticalLayout.addWidget(self.page4Button)
        self.page5Button = QtWidgets.QPushButton(self.groupBox_2)
        self.page5Button.setCheckable(True)
        self.page5Button.setObjectName("page5Button")
        self.verticalLayout.addWidget(self.page5Button)
        spacerItem = QtWidgets.QSpacerItem(20, 463, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.titleGroupBox = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleGroupBox.sizePolicy().hasHeightForWidth())
        self.titleGroupBox.setSizePolicy(sizePolicy)
        self.titleGroupBox.setMinimumSize(QtCore.QSize(0, 55))
        self.titleGroupBox.setStyleSheet("")
        self.titleGroupBox.setTitle("")
        self.titleGroupBox.setObjectName("titleGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleGroupBox)
        self.horizontalLayout_2.setContentsMargins(9, 5, 15, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.StrangerButton = QtWidgets.QPushButton(self.titleGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StrangerButton.sizePolicy().hasHeightForWidth())
        self.StrangerButton.setSizePolicy(sizePolicy)
        self.StrangerButton.setMinimumSize(QtCore.QSize(140, 37))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/home/icon/人员_people_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/home/icon/人员屏蔽_people-unknown.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.StrangerButton.setIcon(icon)
        self.StrangerButton.setCheckable(True)
        self.StrangerButton.setChecked(True)
        self.StrangerButton.setObjectName("StrangerButton")
        self.horizontalLayout_2.addWidget(self.StrangerButton)
        spacerItem2 = QtWidgets.QSpacerItem(260, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.CameraButton = QtWidgets.QPushButton(self.titleGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CameraButton.sizePolicy().hasHeightForWidth())
        self.CameraButton.setSizePolicy(sizePolicy)
        self.CameraButton.setMinimumSize(QtCore.QSize(120, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/home/icon/Camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CameraButton.setIcon(icon1)
        self.CameraButton.setObjectName("CameraButton")
        self.horizontalLayout_2.addWidget(self.CameraButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.miniButton = QtWidgets.QPushButton(self.titleGroupBox)
        self.miniButton.setMinimumSize(QtCore.QSize(34, 30))
        self.miniButton.setText("")
        self.miniButton.setObjectName("miniButton")
        self.horizontalLayout_2.addWidget(self.miniButton)
        self.maxiButton = QtWidgets.QPushButton(self.titleGroupBox)
        self.maxiButton.setMinimumSize(QtCore.QSize(35, 30))
        self.maxiButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/home/icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/home/icon/split.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.maxiButton.setIcon(icon2)
        self.maxiButton.setIconSize(QtCore.QSize(30, 30))
        self.maxiButton.setCheckable(True)
        self.maxiButton.setChecked(False)
        self.maxiButton.setObjectName("maxiButton")
        self.horizontalLayout_2.addWidget(self.maxiButton)
        self.closeButton = QtWidgets.QPushButton(self.titleGroupBox)
        self.closeButton.setMinimumSize(QtCore.QSize(34, 30))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout_5.addWidget(self.titleGroupBox)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("#stackedWidget{\n"
"background-color: rgb(157, 157, 157);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.out_video = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_video.sizePolicy().hasHeightForWidth())
        self.out_video.setSizePolicy(sizePolicy)
        self.out_video.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.out_video.setText("")
        self.out_video.setAlignment(QtCore.Qt.AlignCenter)
        self.out_video.setObjectName("out_video")
        self.verticalLayout_8.addWidget(self.out_video)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("#page_2{\n"
"background-color: rgb(238, 241, 246);\n"
"}\n"
"#groupBox_5{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 40px;\n"
"    border: 2px solid rgb(198, 198, 198);\n"
"}\n"
"#alarmlabel{\n"
"    image: url(:/home/icon/条形图_chart-histogram-two.png);\n"
"}\n"
"\n"
"QAbstractItemView {\n"
"font: bold 10pt \"DengXian\";\n"
"}")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(16, 9, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnLoadData = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadData.sizePolicy().hasHeightForWidth())
        self.btnLoadData.setSizePolicy(sizePolicy)
        self.btnLoadData.setMinimumSize(QtCore.QSize(110, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/home/icon/刷新_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLoadData.setIcon(icon3)
        self.btnLoadData.setIconSize(QtCore.QSize(16, 16))
        self.btnLoadData.setObjectName("btnLoadData")
        self.horizontalLayout_7.addWidget(self.btnLoadData)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.alarmlabel = QtWidgets.QLabel(self.groupBox_5)
        self.alarmlabel.setMinimumSize(QtCore.QSize(35, 0))
        self.alarmlabel.setText("")
        self.alarmlabel.setObjectName("alarmlabel")
        self.horizontalLayout_7.addWidget(self.alarmlabel)
        spacerItem5 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.testLayout = QtWidgets.QVBoxLayout()
        self.testLayout.setContentsMargins(9, 18, 9, 9)
        self.testLayout.setObjectName("testLayout")
        self.verticalLayout_7.addLayout(self.testLayout)
        self.verticalLayout_7.setStretch(1, 10)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("/*QStackedWidget#stackedWidget{background-color: rgb(238, 241, 246);}*/\n"
"#page_3{\n"
"background-color: rgb(238, 241, 246);\n"
"}\n"
"#groupBox_6{\n"
"    border: none;\n"
"    border-radius: 40px;\n"
"    border: 2px solid rgb(198, 198, 198);\n"
"}\n"
"#returnBtn{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    image: url(:/home/icon/left.png);\n"
"}\n"
"#returnBtn:hover{background-color: rgb(222, 222, 222);}\n"
"#returnBtn:pressed{background-color: rgb(189, 189, 189);}\n"
"#btn_play{\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"#btn_play:hover{background-color: rgb(222, 222, 222);}\n"
"#btn_play:pressed{background-color: rgb(189, 189, 189);}\n"
"#btn_stop{\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    image: url(:/home/icon/stop.png);\n"
"}\n"
"#btn_stop:hover{background-color: rgb(222, 222, 222);}\n"
"#btn_stop:pressed{background-color: rgb(189, 189, 189);}\n"
"#medialabel{\n"
"    image: url(:/home/icon/movie.png);\n"
"}\n"
"#audiolabel{\n"
"    image: url(:/home/icon/volume-notice.png);\n"
"}\n"
"#zoomBtn{\n"
"    font: 75 14pt \"Arial\";\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"#zoomBtn:hover{background-color: rgb(222, 222, 222);}\n"
"#zoomBtn:pressed{background-color: rgb(189, 189, 189);}")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setContentsMargins(9, -1, 9, 9)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(35, 4, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.returnBtn = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.returnBtn.sizePolicy().hasHeightForWidth())
        self.returnBtn.setSizePolicy(sizePolicy)
        self.returnBtn.setMinimumSize(QtCore.QSize(40, 22))
        self.returnBtn.setText("")
        self.returnBtn.setObjectName("returnBtn")
        self.horizontalLayout_8.addWidget(self.returnBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.medialabel = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medialabel.sizePolicy().hasHeightForWidth())
        self.medialabel.setSizePolicy(sizePolicy)
        self.medialabel.setMinimumSize(QtCore.QSize(30, 30))
        self.medialabel.setText("")
        self.medialabel.setObjectName("medialabel")
        self.horizontalLayout_8.addWidget(self.medialabel)
        spacerItem7 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.wgt_video = QVideoWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_video.sizePolicy().hasHeightForWidth())
        self.wgt_video.setSizePolicy(sizePolicy)
        self.wgt_video.setMinimumSize(QtCore.QSize(0, 510))
        self.wgt_video.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.wgt_video.setObjectName("wgt_video")
        self.verticalLayout_3.addWidget(self.wgt_video)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(18, -1, 25, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.btn_play = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_play.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_play.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/home/icon/pause-one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/home/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_play.setIcon(icon4)
        self.btn_play.setIconSize(QtCore.QSize(30, 30))
        self.btn_play.setCheckable(True)
        self.btn_play.setChecked(False)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_3.addWidget(self.btn_play)
        self.btn_stop = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_stop.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_stop.setMaximumSize(QtCore.QSize(100, 25))
        self.btn_stop.setText("")
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_3.addWidget(self.btn_stop)
        self.zoomBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.zoomBtn.setMinimumSize(QtCore.QSize(35, 35))
        self.zoomBtn.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/home/icon/右1_right-one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomBtn.setIcon(icon5)
        self.zoomBtn.setIconSize(QtCore.QSize(26, 26))
        self.zoomBtn.setCheckable(False)
        self.zoomBtn.setObjectName("zoomBtn")
        self.horizontalLayout_3.addWidget(self.zoomBtn)
        self.sld_video = myVideoSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sld_video.sizePolicy().hasHeightForWidth())
        self.sld_video.setSizePolicy(sizePolicy)
        self.sld_video.setMinimumSize(QtCore.QSize(410, 20))
        self.sld_video.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sld_video.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"padding: 3px;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"    border-image: url(:/home/icon/shield-add.png);\n"
"     width:20px;\n"
"    height:20x;\n"
"     margin: -10px -10px -10px -10px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.sld_video.setMaximum(100)
        self.sld_video.setOrientation(QtCore.Qt.Horizontal)
        self.sld_video.setObjectName("sld_video")
        self.horizontalLayout_3.addWidget(self.sld_video)
        self.lab_video = QtWidgets.QLabel(self.groupBox_6)
        self.lab_video.setObjectName("lab_video")
        self.horizontalLayout_3.addWidget(self.lab_video)
        spacerItem9 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.audiolabel = QtWidgets.QLabel(self.groupBox_6)
        self.audiolabel.setMinimumSize(QtCore.QSize(23, 0))
        self.audiolabel.setText("")
        self.audiolabel.setObjectName("audiolabel")
        self.horizontalLayout_3.addWidget(self.audiolabel)
        self.sld_audio = QtWidgets.QSlider(self.groupBox_6)
        self.sld_audio.setMinimumSize(QtCore.QSize(100, 0))
        self.sld_audio.setMaximumSize(QtCore.QSize(150, 20))
        self.sld_audio.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"    border-image: url(:/home/icon/dot.png);\n"
"     width:15px;\n"
"     margin: -7px -7px -7px -7px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.sld_audio.setProperty("value", 99)
        self.sld_audio.setOrientation(QtCore.Qt.Horizontal)
        self.sld_audio.setObjectName("sld_audio")
        self.horizontalLayout_3.addWidget(self.sld_audio)
        self.lab_audio = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_audio.sizePolicy().hasHeightForWidth())
        self.lab_audio.setSizePolicy(sizePolicy)
        self.lab_audio.setMinimumSize(QtCore.QSize(70, 0))
        self.lab_audio.setObjectName("lab_audio")
        self.horizontalLayout_3.addWidget(self.lab_audio)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 34)
        self.verticalLayout_3.setStretch(2, 3)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("#page_4{background-color: rgb(238, 241, 246);}\n"
"#groupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 40px;\n"
"    border: 2px solid rgb(198, 198, 198);\n"
"}\n"
"#datelabel{\n"
"    image: url(:/home/icon/calendar.png);\n"
"    background: transparent;\n"
"}\n"
"#historylabel{\n"
"    image: url(:/home/icon/history-query.png);\n"
"    background: transparent;\n"
"}\n"
"#queryButton{\n"
"    border-radius: 18px;\n"
"    background-color: rgb(255, 126, 45);\n"
"    font: 87 12pt \"Source Han Serif SC Heavy\";\n"
"    font: 12pt \"方正粗黑宋简体\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"}\n"
"#queryButton:hover{\n"
"    background-color: rgb(244, 121, 43);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#queryButton:pressed{\n"
"    background-color: rgb(222, 109, 39);\n"
"}\n"
"#dateEdit{\n"
"    font: bold 10pt \"DengXian\";\n"
"}\n"
"\n"
"#qt_calendar_calendarview {\n"
"background: white;\n"
"}\n"
"/*\n"
"#qt_calendar_navigationbar {\n"
"background: rgba(215, 215, 215, 255);\n"
"}*/\n"
"QToolButton {\n"
"icon-size: 30px, 30px;\n"
"/*width: 80px;\n"
"height: 30px;*/\n"
"}\n"
"QToolButton#qt_calendar_prevmonth {\n"
"/*background: green;*/\n"
"/*width: 40px;*/\n"
"qproperty-icon: url(:/home/icon/go-start.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth {\n"
"/*background: blue;\n"
"width: 40px;*/\n"
"qproperty-icon: url(:/home/icon/go-end.png);\n"
"}\n"
"QToolButton#qt_calendar_monthbutton {\n"
"/*background: yellow;*/\n"
"    font: bold 11pt \"DengXian\";\n"
"color: rgb(0, 0, 0);\n"
"padding-right: 20px;\n"
"}\n"
"QToolButton#qt_calendar_yearbutton {\n"
"/*background: magenta;*/\n"
"color: rgb(0, 0, 0);\n"
"    font: bold 11pt \"DengXian\";\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::menu-indicator{\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: center right;\n"
"right: 3px;\n"
"width: 10px;\n"
"}\n"
"QAbstractItemView {\n"
"color: black;\n"
"selection-color: white;\n"
"selection-background-color: rgb(25, 125, 255);\n"
"font: bold 10pt \"DengXian\";\n"
"}\n"
"QAbstractItemView:disabled {\n"
"color: rgb(200, 200, 200);\n"
"}")
        self.page_4.setObjectName("page_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_2.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.page_4)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.datelabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datelabel.sizePolicy().hasHeightForWidth())
        self.datelabel.setSizePolicy(sizePolicy)
        self.datelabel.setMinimumSize(QtCore.QSize(25, 0))
        self.datelabel.setText("")
        self.datelabel.setObjectName("datelabel")
        self.horizontalLayout_5.addWidget(self.datelabel)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setMinimumSize(QtCore.QSize(280, 40))
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.dateEdit)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.queryButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryButton.sizePolicy().hasHeightForWidth())
        self.queryButton.setSizePolicy(sizePolicy)
        self.queryButton.setMinimumSize(QtCore.QSize(137, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/home/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.queryButton.setIcon(icon6)
        self.queryButton.setObjectName("queryButton")
        self.horizontalLayout_5.addWidget(self.queryButton)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.historylabel = QtWidgets.QLabel(self.groupBox)
        self.historylabel.setMinimumSize(QtCore.QSize(30, 0))
        self.historylabel.setText("")
        self.historylabel.setObjectName("historylabel")
        self.horizontalLayout_5.addWidget(self.historylabel)
        spacerItem14 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.searchLayout = QtWidgets.QVBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.verticalLayout_12.addLayout(self.searchLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("#page_5{background-color: rgb(238, 241, 246);}\n"
"#groupBox_3{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 40px;\n"
"    border: 2px solid rgb(198, 198, 198);\n"
"}\n"
"#userpagelabel{\n"
"    image: url(:/home/icon/用户_user.png);\n"
"}\n"
"#userAddBtn{\n"
"    border-radius: 18px;\n"
"    background-color: rgb(0, 151, 63);\n"
"    font: 87 12pt \"Source Han Serif SC Heavy\";\n"
"    font: 12pt \"方正粗黑宋简体\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"}\n"
"#userAddBtn:hover{\n"
"    background-color: rgb(0, 126, 52);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#userAddBtn:pressed{\n"
"    background-color: rgb(0, 108, 45);\n"
"}\n"
"QAbstractItemView {\n"
"font: bold 10pt \"DengXian\";\n"
"}")
        self.page_5.setObjectName("page_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_10.setContentsMargins(36, 36, 36, 36)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_5)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_13.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.userpagelabel = QtWidgets.QLabel(self.groupBox_3)
        self.userpagelabel.setMinimumSize(QtCore.QSize(35, 0))
        self.userpagelabel.setText("")
        self.userpagelabel.setObjectName("userpagelabel")
        self.horizontalLayout_6.addWidget(self.userpagelabel)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.userAddBtn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userAddBtn.sizePolicy().hasHeightForWidth())
        self.userAddBtn.setSizePolicy(sizePolicy)
        self.userAddBtn.setMinimumSize(QtCore.QSize(120, 40))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/home/icon/添加用户_add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userAddBtn.setIcon(icon7)
        self.userAddBtn.setIconSize(QtCore.QSize(20, 20))
        self.userAddBtn.setObjectName("userAddBtn")
        self.horizontalLayout_6.addWidget(self.userAddBtn)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.userLayout = QtWidgets.QVBoxLayout()
        self.userLayout.setContentsMargins(-1, 9, -1, -1)
        self.userLayout.setObjectName("userLayout")
        self.verticalLayout_13.addLayout(self.userLayout)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout_9.addWidget(self.frame_3)
        self.verticalLayout_11.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.page1Button.setText(_translate("MainWindow", "监 控 画 面"))
        self.page2Button.setText(_translate("MainWindow", "报 警 记 录"))
        self.page4Button.setText(_translate("MainWindow", "回 放 查 询"))
        self.page5Button.setText(_translate("MainWindow", "用 户 信 息"))
        self.StrangerButton.setText(_translate("MainWindow", "关闭陌生人识别"))
        self.CameraButton.setText(_translate("MainWindow", "选择摄像头"))
        self.btnLoadData.setText(_translate("MainWindow", " 刷 新"))
        self.btn_play.setShortcut(_translate("MainWindow", "Space"))
        self.zoomBtn.setText(_translate("MainWindow", "1.0×"))
        self.lab_video.setText(_translate("MainWindow", "00:00:00"))
        self.lab_audio.setText(_translate("MainWindow", "volume:100%"))
        self.queryButton.setText(_translate("MainWindow", "查 询"))
        self.userAddBtn.setText(_translate("MainWindow", "添加用户"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
from myDesign_win.myvideoslider import myVideoSlider
import apprcc_rc
