# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginSurface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(527, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(10, 10))
        Dialog.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QFrame#frame{\n"
"    border-radius:35px;\n"
"    border-image: url(:/login/icon/loginbackground.jpg);\n"
"}\n"
"\n"
"#frame_2{\n"
"    border-radius:35px;\n"
"    background-color: rgba(206, 206, 206, 70);\n"
"}\n"
"\n"
"QGroupBox#groupBox{\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#appNameLabel{\n"
"    background: transparent;\n"
"    color: rgb(232, 233, 234);\n"
"    font: 14pt \"hooge 05_54\";\n"
"}\n"
"\n"
"QLabel#userNameLabel{\n"
"    background: transparent;\n"
"    font: 14pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#passwordLabel{\n"
"    background: transparent;\n"
"    font: 14pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#passwordConfirmLabel{\n"
"    background: transparent;\n"
"    font: 14pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#loginMiniButton{\n"
"    border-radius:10px;\n"
"    image: url(:/login/icon/minus.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"#loginMiniButton:hover{\n"
"    background-color: rgba(94, 99, 102, 150);\n"
"}\n"
"\n"
"#loginMiniButton:pressed{\n"
"    background-color: rgba(69, 73, 75, 220);\n"
"}\n"
"\n"
"#loginCloseButton{\n"
"    border-radius:10px;\n"
"    image: url(:/login/icon/close.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"#loginCloseButton:hover{\n"
"    background-color: rgba(94, 99, 102, 150);\n"
"}\n"
"\n"
"#loginCloseButton:pressed{\n"
"    background-color: rgba(69, 73, 75, 220);\n"
"}\n"
"\n"
"#loginButton{\n"
"    border-radius:10px;\n"
"    background: transparent;\n"
"    font: 14pt \"幼圆\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"}\n"
"\n"
"#loginButton:hover{\n"
"    background-color: rgba(62, 64, 71, 150);\n"
"    font: 14pt \"幼圆\";\n"
"    color: rgba(255, 255, 255, 220);\n"
"}\n"
"\n"
"#loginButton:pressed{\n"
"    background-color: rgba(77, 77, 77, 160);\n"
"    font: 14pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-bottom: 2px solid rgba(255, 255, 255, 200);\n"
"    font: 12pt \"MS Reference Sans Serif\";\n"
"    font: 16pt \"Cascadia Code\";\n"
"    padding: 4px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(6, 7, 6, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(360, 50))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.appNameLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appNameLabel.sizePolicy().hasHeightForWidth())
        self.appNameLabel.setSizePolicy(sizePolicy)
        self.appNameLabel.setMinimumSize(QtCore.QSize(224, 0))
        self.appNameLabel.setText("")
        self.appNameLabel.setPixmap(QtGui.QPixmap(":/login/icon/applabel.png"))
        self.appNameLabel.setObjectName("appNameLabel")
        self.horizontalLayout_4.addWidget(self.appNameLabel)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.loginMiniButton = QtWidgets.QPushButton(self.groupBox)
        self.loginMiniButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loginMiniButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loginMiniButton.setText("")
        self.loginMiniButton.setObjectName("loginMiniButton")
        self.horizontalLayout_4.addWidget(self.loginMiniButton)
        spacerItem1 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.loginCloseButton = QtWidgets.QPushButton(self.groupBox)
        self.loginCloseButton.setMinimumSize(QtCore.QSize(40, 40))
        self.loginCloseButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loginCloseButton.setText("")
        self.loginCloseButton.setObjectName("loginCloseButton")
        self.horizontalLayout_4.addWidget(self.loginCloseButton)
        self.verticalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, -1, 8, -1)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userNameLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userNameLabel.sizePolicy().hasHeightForWidth())
        self.userNameLabel.setSizePolicy(sizePolicy)
        self.userNameLabel.setMinimumSize(QtCore.QSize(70, 50))
        self.userNameLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.userNameLabel.setAutoFillBackground(False)
        self.userNameLabel.setObjectName("userNameLabel")
        self.horizontalLayout.addWidget(self.userNameLabel)
        self.userNameEdit = QtWidgets.QLineEdit(self.frame_2)
        self.userNameEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.userNameEdit.setObjectName("userNameEdit")
        self.horizontalLayout.addWidget(self.userNameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 8, -1)
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.passwordLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLabel.sizePolicy().hasHeightForWidth())
        self.passwordLabel.setSizePolicy(sizePolicy)
        self.passwordLabel.setMinimumSize(QtCore.QSize(70, 50))
        self.passwordLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.passwordLabel.setObjectName("passwordLabel")
        self.horizontalLayout_2.addWidget(self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordEdit.sizePolicy().hasHeightForWidth())
        self.passwordEdit.setSizePolicy(sizePolicy)
        self.passwordEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout_2.addWidget(self.passwordEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.loginButton = QtWidgets.QPushButton(self.frame_2)
        self.loginButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginButton.sizePolicy().hasHeightForWidth())
        self.loginButton.setSizePolicy(sizePolicy)
        self.loginButton.setMinimumSize(QtCore.QSize(220, 40))
        self.loginButton.setMaximumSize(QtCore.QSize(300, 40))
        self.loginButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.userNameLabel.setText(_translate("Dialog", " 用户名:"))
        self.passwordLabel.setText(_translate("Dialog", " 密 码"))
        self.loginButton.setText(_translate("Dialog", "登 录"))
import apprcc_rc
